# Generated by Django 5.1.4 on 2025-01-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.TextField(blank=True, db_column='Material Code', null=True)),
                ('material_description', models.TextField(blank=True, db_column='Material Description', null=True)),
                ('unit', models.TextField(blank=True, db_column='Unit', null=True)),
                ('date', models.TextField(blank=True, db_column='Date', null=True)),
                ('open_stock', models.TextField(blank=True, db_column='Open Stock', null=True)),
                ('material_issued', models.TextField(blank=True, db_column='Material Issued', null=True)),
                ('material_received', models.TextField(blank=True, db_column='Material Received', null=True)),
                ('closing_stock', models.TextField(blank=True, db_column='Closing Stock', null=True)),
                ('prefix', models.TextField(blank=True, db_column='Prefix', null=True)),
                ('type', models.TextField(blank=True, db_column='Type', null=True)),
                ('pdt', models.TextField(blank=True, db_column='PDT', null=True)),
                ('bfp', models.TextField(blank=True, db_column='BFP', null=True)),
                ('price', models.TextField(blank=True, db_column='Price', null=True)),
            ],
            options={
                'db_table': 'INVENTORY_TABLE',
                'managed': False,
            },
        ),
    ]
